services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  python-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
